#root -l -b -q dataMCPlot.C\(1,\"hlept1_Pt\"\)
#root -l -b -q dataMCPlot.C\(1,\"hlept2_Pt\"\)
#root -l -b -q dataMCPlot.C\(1,\"hlept1_Eta\"\)
#root -l -b -q dataMCPlot.C\(1,\"hlept2_Eta\"\)
root -l -b -q dataMCPlot.C\(1,\"hZmass\"\)
root -l -b -q dataMCPlot.C\(1,\"hphoEt\"\)
#root -l -b -q dataMCPlot.C\(1,\"hphoEta\"\)
root -l -b -q dataMCPlot.C\(1,\"hmllg\"\)
#root -l -b -q dataMCPlot.C\(1,\"hdRPhoLep\"\)
#root -l -b -q dataMCPlot.C\(1,\"hnVtx\"\)
root -l -b -q dataMCPlot.C\(1,\"hssmva\"\)

#root -l -b -q dataMCPlot.C\(0,\"hlept1_Pt\"\)
#root -l -b -q dataMCPlot.C\(0,\"hlept2_Pt\"\)
#root -l -b -q dataMCPlot.C\(0,\"hlept1_Eta\"\)
#root -l -b -q dataMCPlot.C\(0,\"hlept2_Eta\"\)
root -l -b -q dataMCPlot.C\(0,\"hZmass\"\)
root -l -b -q dataMCPlot.C\(0,\"hphoEt\"\)
#root -l -b -q dataMCPlot.C\(0,\"hphoEta\"\)
root -l -b -q dataMCPlot.C\(0,\"hmllg\"\)
#root -l -b -q dataMCPlot.C\(0,\"hdRPhoLep\"\)
#root -l -b -q dataMCPlot.C\(0,\"hnVtx\"\)
root -l -b -q dataMCPlot.C\(0,\"hssmva\"\)


#root -l dataMCPlot.C\(1,\"hnVtx\"\)
#root -l dataMCPlot.C\(1,\"hphoEt\"\)
#root -l dataMCPlot.C\(1,\"hmllg\"\)
#root -l dataMCPlot.C\(1,\"hZmass\"\)
#root -l dataMCPlot.C\(0,\"hZmass\"\)
