'''
root -l -b -q IdPlot.C\(1,\"hlepd0_lead\"\)
root -l -b -q IdPlot.C\(1,\"hlepdz_lead\"\)
root -l -b -q IdPlot.C\(1,\"hSIP_lead\"\)
root -l -b -q IdPlot.C\(1,\"hchiso_lead\"\)
root -l -b -q IdPlot.C\(1,\"hphoiso_lead\"\)
root -l -b -q IdPlot.C\(1,\"hneuiso_lead\"\)
root -l -b -q IdPlot.C\(1,\"hmva_lead\"\)
root -l -b -q IdPlot.C\(1,\"hlepd0_trail\"\)
root -l -b -q IdPlot.C\(1,\"hlepdz_trail\"\)
root -l -b -q IdPlot.C\(1,\"hSIP_trail\"\)
root -l -b -q IdPlot.C\(1,\"hchiso_trail\"\)
root -l -b -q IdPlot.C\(1,\"hphoiso_trail\"\)
root -l -b -q IdPlot.C\(1,\"hneuiso_trail\"\)
root -l -b -q IdPlot.C\(1,\"hmva_trail\"\)

root -l -b -q IdPlot.C\(0,\"hlepd0_lead\"\)
root -l -b -q IdPlot.C\(0,\"hlepdz_lead\"\)
root -l -b -q IdPlot.C\(0,\"hSIP_lead\"\)
root -l -b -q IdPlot.C\(0,\"hchiso_lead\"\)
root -l -b -q IdPlot.C\(0,\"hphoiso_lead\"\)
root -l -b -q IdPlot.C\(0,\"hneuiso_lead\"\)
root -l -b -q IdPlot.C\(0,\"hsigEOverE_lead\"\)
root -l -b -q IdPlot.C\(0,\"hmuSta\"\)
root -l -b -q IdPlot.C\(0,\"hmuPixhit\"\)
root -l -b -q IdPlot.C\(0,\"hmutrkLayer\"\)
root -l -b -q IdPlot.C\(0,\"hlepd0_trail\"\)
root -l -b -q IdPlot.C\(0,\"hlepdz_trail\"\)
root -l -b -q IdPlot.C\(0,\"hSIP_trail\"\)
root -l -b -q IdPlot.C\(0,\"hchiso_trail\"\)
root -l -b -q IdPlot.C\(0,\"hphoiso_trail\"\)
root -l -b -q IdPlot.C\(0,\"hneuiso_trail\"\)
root -l -b -q IdPlot.C\(0,\"hsigEOverE_trail\"\)

'''

root -l -b -q IdPlot.C\(1,\"hphoHoE\"\)
root -l -b -q IdPlot.C\(1,\"hphochiso\"\) 
root -l -b -q IdPlot.C\(1,\"hphowchiso\"\)
root -l -b -q IdPlot.C\(1,\"hphosieie\"\) 
root -l -b -q IdPlot.C\(1,\"hsieip\"\) 
root -l -b -q IdPlot.C\(1,\"hetawidth\"\) 
root -l -b -q IdPlot.C\(1,\"hphiwidth\"\)
root -l -b -q IdPlot.C\(1,\"hscRawE\"\)
root -l -b -q IdPlot.C\(1,\"hs4\"\)
root -l -b -q IdPlot.C\(1,\"hr9\"\)
root -l -b -q IdPlot.C\(1,\"hphophi\"\)
root -l -b -q IdPlot.C\(1,\"hrho\"\)
root -l -b -q IdPlot.C\(1,\"hphossmva\"\)

#root -l -b -q IdPlot.C\(0,\"hphoHoE\"\)
#root -l -b -q IdPlot.C\(0,\"hphochiso\"\) 
#root -l -b -q IdPlot.C\(0,\"hphowchiso\"\)
#root -l -b -q IdPlot.C\(0,\"hphosieie\"\) 
#root -l -b -q IdPlot.C\(0,\"hsieip\"\) 
#root -l -b -q IdPlot.C\(0,\"hetawidth\"\) 
#root -l -b -q IdPlot.C\(0,\"hphiwidth\"\)
#root -l -b -q IdPlot.C\(0,\"hscRawE\"\)
#root -l -b -q IdPlot.C\(0,\"hs4\"\)
#root -l -b -q IdPlot.C\(0,\"hr9\"\)
#root -l -b -q IdPlot.C\(0,\"hphophi\"\)
#root -l -b -q IdPlot.C\(0,\"hrho\"\)
