#root -l -b -q xdataMCPlot.C\(1,\"data\"\)
root -l -b -q xdataMCPlot.C\(1,\"Zg\"\)
#root -l -b -q xdataMCPlot.C\(1,\"ZJet\"\)
#root -l -b -q xdataMCPlot.C\(1,\"TT_\"\)
#root -l -b -q xdataMCPlot.C\(1,\"WWTo2L2Nu\"\)
#root -l -b -q xdataMCPlot.C\(1,\"WWToLNuQQ\"\)
#root -l -b -q xdataMCPlot.C\(1,\"WZTo3LNu\"\)
#root -l -b -q xdataMCPlot.C\(1,\"WZTo2L2Q\"\)
#root -l -b -q xdataMCPlot.C\(1,\"ZZTo2L2Nu\"\)
#root -l -b -q xdataMCPlot.C\(1,\"ZZTo2L2Q\"\)
#root -l -b -q xdataMCPlot.C\(1,\"ZZTo4L\"\)

#root -l -b -q xdataMCPlot.C\(0,\"data\"\)
root -l -b -q xdataMCPlot.C\(0,\"Zg\"\)
#root -l -b -q xdataMCPlot.C\(0,\"ZJet\"\)
#root -l -b -q xdataMCPlot.C\(0,\"TT_\"\)
#root -l -b -q xdataMCPlot.C\(0,\"WWTo2L2Nu\"\)
#root -l -b -q xdataMCPlot.C\(0,\"WWToLNuQQ\"\)
#root -l -b -q xdataMCPlot.C\(0,\"WZTo3LNu\"\)
#root -l -b -q xdataMCPlot.C\(0,\"WZTo2L2Q\"\)
#root -l -b -q xdataMCPlot.C\(0,\"ZZTo2L2Nu\"\)
#root -l -b -q xdataMCPlot.C\(0,\"ZZTo2L2Q\"\)
#root -l -b -q xdataMCPlot.C\(0,\"ZZTo4L\"\)

